version: "3.7"

networks:
  laravel:
    driver: bridge  

services:

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/
    #    restart: always
    volumes:
      - ./src:/var/www
    networks:
      - laravel
#    environment:
#      - "XDEBUG_CONFIG=client_host=localhost client_port=9003 mode=debug start_with_request=1 idekey=PHPSTORM discover_client_host=on"
#      - "XDEBUG_MODE=debug"
#      - "PHP_IDE_CONFIG=serverName=xdebug-docker"

  nginx:
    container_name: nginx
    build: ./conf/nginx
    #    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./src:/var/www
    networks:
      - laravel
    depends_on:
      - app
